### ISSUE TITLE
Unable to run *.json postman collection

### ISSUE THREAD

**Issue by wfs** [eridem/vscode-postman#1]
Hi. Thanks for the extension and understand it is early beta. Just tried to run json file but after selecting file nothing happened e.g. did not get show 'Environments' etc as is in your gif.
![2016-10-24_11-59-18](https://cloud.githubusercontent.com/assets/980502/19631028/ce3a9738-99e1-11e6-8a80-b4d4f631521d.png)

**Comment by eridem** [comment]
Thanks for report :-)
Are the environment files *.postman_environment.json inside the folder too?

They may be a known issue: I just tested it with collections that have folders.
I will revise the extension today after work and let you know 👍

![image 2](https://cloud.githubusercontent.com/assets/436978/19634091/418ad538-99b8-11e6-9750-e9be8bc8113a.png)

**Comment by eridem** [comment]
hi @wfs,
I did a patch to support collections exported as v1 and v2. I saw that v1 was not supported and now it is.
Can you let me know if the latest version of the extension solve your problem?
Thanks a lot!

**Comment by eridem** [comment]
hi @wfs, I will close the issue. Please let me know if you have other problems.
