### ISSUE TITLE
feature: --work-dir option

### ISSUE THREAD

**Issue by TonyTong502** [eridem/vscode-postman#18]
is it possible to add --work-dir option? this is required for api tests to upload a file

https://github.com/postmanlabs/newman#command-line-options
--working-dir <path>
Set the path of the working directory to use while reading files with relative paths. Default to current directory.

postman client reference: [link](https://support.postman.com/hc/en-us/articles/360023574653-Storage-of-file-Working-Directory-in-reference-for-collections)

**Comment by eridem** [comment]
Thanks for your comment.

I released the version `2.1.0` now where you can select the working directory :-)
