### ISSUE TITLE
Cmd+Q is for quit application in Mac OSX

### ISSUE THREAD

**Issue by corretge** [eridem/vscode-postman#3]
Congrats for your extension but I have an issue:

When I try to exit from vscode on my Mac, with Cmd+Q, your extension is triggered.

Is it possible to configure the shortcut?

Thanks

**Comment by eridem** [comment]
Hi @corretge,

Thanks for the feedback. At the moment it is not possible, but I will do a patch in the following days for it 👍

**Comment by eridem** [comment]
hi @corretge, I fixed this issue together with other ones.

I just released a new version `0.5.2` with the hotkey `Cmd+R`.

Thanks!
