### ISSUE TITLE
can't find the document with the results in a new tab.

### ISSUE THREAD

**Issue by lucafregoso** [eridem/vscode-postman#4]
I can see the output but it doesn't open the yaml file (and it doesn't create it)
<img width="1134" alt="schermata 2017-05-25 alle 15 12 00" src="https://cloud.githubusercontent.com/assets/184508/26451498/8fba6772-415c-11e7-90e3-6ab9f9b8c0e9.png">

**Comment by eridem** [comment]
Can you check you have the following setting?:

```
  "postman.showResultsInNewDocument": true,
```

**Comment by lucafregoso** [comment]
yes I put that config line but it doesn't solve the problem

**Comment by eridem** [comment]
Which OS are you using?

Can you check if any of these folders exists?

`/tmp/vscode-postman-results`

`C:\Windows\Temp\vscode-postman-results`

**Comment by eridem** [comment]
As well, if they have write access because it will place the files there.

**Comment by lucafregoso** [comment]
MacOS Sierra..I just created the folder in tmp, it didn't exist

**Comment by lucafregoso** [comment]
but unfortunately still the same error

**Comment by eridem** [comment]
Oh well, if it is on Mac, the right folder should be:

`$TMPDIR/vscode-postman-results`

I am being testing it on Windows and Linux. I will do more tests on MAC and back to you.

**Comment by eridem** [comment]
hi @lucafregoso, I am being testing it with macOS Sierra 10.12.4.

I found a bug with reports, but not sure if this resolve your problem. I create a new version tagged with 0.5.2 (https://marketplace.visualstudio.com/items?itemName=eridem.vscode-postman). 

Can you update it on your VSCode as soon it appears available?

### For testing:

I exported the default `Echo` collection from Postman to test it. Can you try it out?

You can download the file from here: https://github.com/eridem/vscode-postman/blob/master/test/echo-v2.postman_collection.json

**Comment by lucafregoso** [comment]
hi @eridem , unfortunately it doesn't solve the problem
