### ISSUE TITLE
Upgrade Newman Version

### ISSUE THREAD

**Issue by DannyDainton** [eridem/vscode-postman#6]
Hey @eridem 

Do you have plans to update the version of Newman that's being used in the extension?

Currently, the version in the `package.json` file is `3.6.0` but Newman has now moved to V4.

**Comment by eridem** [comment]
Yo @DannyDainton 🙌 

I will have a look and see if I can do a patch and back to you in the incoming days :-)

Thanks for reporting!

**Comment by eridem** [comment]
It took a while, but finally we have version 4!
