### ISSUE TITLE
Tests with Forwarding (Status 307) behave different than Postman

### ISSUE THREAD

**Issue by DrNiels** [eridem/vscode-postman#7]
I have some tests in Postman that I wanted to move to Visual Studio Code, using your plugin.

One of my tests access an access point that forwards to another location via HTML status 307. I verify the response with the following tests:

    pm.test("Status code is 307", function () {
         pm.response.to.have.status(307);
    });
    pm.test("Location is present", function () {
        pm.response.to.have.header("Location");
    });
    tests["Location is correct"] = (/^https:\/\/my-awesome-dummy-address.com/.test(pm.response.headers.get('Location')));

This is working successfully with the "original" Postman. However, using your Plugin, I receive a code 200, so I assume that the tests run on the forwarded address and thus fail. It would be nice if the Postman program and VSC plugin would behave consistently here.

**Comment by eridem** [comment]
Please verify if the new version solved your issue.

**Comment by DrNiels** [comment]
Unfortunately, it does not. I just installed the newest version in Visual Studio Code 2.0.0 and still get the mentioned status 200.

Is it the correct version? Or do I need to download a beta version or something someplace else?
